---
abstract: 'Tapper - Utilities for Perl based Tapper testing'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Test
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Format::Human::Bytes: 0
  Sys::Info: 0
  Test::More: 0
  parent: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Test
  repository: git://github.com/amd/Tapper-Test.git
version: 3.000011
